# .github/workflows/ci-cd.yml
name: Java CI/CD with Maven

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: maven
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    
    - name: Run tests
      run: mvn test
    
    - name: Upload build artifact
      uses: actions/upload-artifact@v3
      with:
        name: hello-world-app
        path: target/*.jar

  deploy:
    needs: build-and-test
    if: github.event_name == 'push' && (github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master')
    runs-on: ubuntu-latest
    
    steps:
    - name: Download build artifact
      uses: actions/download-artifact@v3
      with:
        name: hello-world-app
    
    # Example deployment step - modify according to your deployment target
    - name: Deploy to server
      run: |
        echo "Deploying application..."
        # Add your deployment commands here
        # Examples:
        # - SSH into your server and copy the JAR file
        # - Deploy to a cloud service like Heroku, AWS, or Azure
        # - Use a specific deployment action from the GitHub Marketplace